### ISSUE TITLE
Unable to enter more than one full stop (.)

### ISSUE THREAD

**Issue by ibbr** [aharen/thaana-keyboard#7] opened 2021-08-04 09:19 UTC
![Snipaste_2021-08-04_14-17-14](https://user-images.githubusercontent.com/34295188/128155943-d5c3ddee-975f-4399-93f8-6416843b257b.png)
As soon as a second full stop is entered, the first one is removed.

**Comment by aharen** [comment] 2021-08-04 15:35
Hi, Thanks for the bug report.

I won't probably have time to investigate this before next week. 

If you do find the cause of this issue please update here or if you find a fix please feel free to send in a pull request.

Thanks

**Comment by aharen** [comment] 2021-09-13 16:41
Hi @ibrahim-rasheed 

Just released a fix for this issue. 

Check from [https://thaana-keyboard.khusaam.com/](https://thaana-keyboard.khusaam.com/)

Thanks

**Closed as completed** 2021-09-17 02:53 UTC
Labels: bug
